#!/bin/bash

if [ "$1"x == "configx" ]; then
	echo graph_title Backup time
	echo graph_vlabel seconds
	echo time.label time
	exit 0
fi

f_log=/opt/var/log/bkp.log

if [ -r "$f_log" ]; then
	time=`grep $'^Finish\t' "$f_log"|tail -1|cut -f3 -d$'\t'`
else
	time=0
fi

echo time.value $time
