#!/bin/bash

f_log=/opt/var/log/bkp.log

if [ -r "$f_log" ]; then
	size=`grep $'^Finish\t' "$f_log"|tail -1|cut -f4 -d$'\t'`
else
	size=0
fi

echo graph_title Backup size
echo graph_vlabel size [B]
echo size.value $size
