#!/bin/bash

if [ "$1"x == "configx" ]; then
	echo graph_title Backup size
	echo graph_vlabel bytes
	echo size.label size
	exit 0
fi

f_log=/opt/var/log/bkp.log

if [ -r "$f_log" ]; then
	size=`grep $'^Finish\t' "$f_log"|tail -1|cut -f4 -d$'\t'`
else
	size=0
fi

echo size.value $size
