#!/bin/bash

if [ "$1"x == "configx" ]; then
	echo graph_title Backup mirror transfer speed
	echo graph_vlabel bytes / second
	echo speed.label speed
	exit 0
fi

f_log=/opt/var/log/bkp-mirror.log

if [ -r "$f_log" ]; then
	speed=`grep "^sent " "$f_log"|tail -1|tr -s '[:space:]'|cut -f7 -d" "`
	speed=`echo "${speed//,}"`
else
	speed=0
fi

echo speed.value $speed
